services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farm_nestjs_api
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres_db:5432/farm_nestjs_api
      NODE_ENV: development
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
