POST http://localhost:3000/farms
content-type: application/json

{
	"producerId": "80f481c5-c52c-4c11-abe8-f2e777335924",
	"name": "Fazendinha 2",
	"city": "Araçatuba",
	"state": "São Paulo",
	"totalArea": 100,
	"vegetationArea": 30,
	"agriculturalArea": 70
}